/*
 * config file for nei server command
 * @author
 * Auto build by NEI Builder
 */
var path = require('path');
module.exports = {
    /* 根目录 */
    webRoot: '',
    /* 视图目录 */
    viewRoot: '/Users/guoquankai/webProject/mainsite-test4/source/views/',
    /* 路由 */
    routes: {
        //"ALL /api/*": "代理所有接口, 这里输入代理服务器地址",
        "GET supervisor/api/statistics/sessionNums": { path: 'get/supervisor/api/statistics/sessionNums/data', id: 13566, group: '默认分组' },
        "GET ics": { name: 'sem落地页', index: 0, list: [{"id":14573,"path":"activity\\sem"}] },
        "GET api/version/check": { path: 'get/api/version/check/data', id: 15499, group: '默认分组' },
        "GET /worksheet/api/transmit/list": { path: 'get/worksheet/api/transmit/list/data', id: 13954, group: '默认分组' },
        "GET /worksheet/api/submit/list": { path: 'get/worksheet/api/submit/list/data', id: 13953, group: '默认分组' },
        "GET /worksheet/api/sheet/user/count": { path: 'get/worksheet/api/sheet/user/count/data', id: 14137, group: '默认分组' },
        "POST /worksheet/api/sheet/transmit": { path: 'post/worksheet/api/sheet/transmit/data', id: 14074, group: '默认分组' },
        "POST /worksheet/api/sheet/search": { path: 'post/worksheet/api/sheet/search/data', id: 13957, group: '默认分组' },
        "POST /worksheet/api/sheet/reply": { path: 'post/worksheet/api/sheet/reply/data', id: 14073, group: '默认分组' },
        "POST /worksheet/api/sheet/modify": { path: 'post/worksheet/api/sheet/modify/data', id: 25597, group: '默认分组' },
        "GET /worksheet/api/sheet/history": { path: 'get/worksheet/api/sheet/history/data', id: 13956, group: '默认分组' },
        "POST /worksheet/api/sheet/handle": { path: 'post/worksheet/api/sheet/handle/data', id: 13973, group: '默认分组' },
        "GET /worksheet/api/sheet/get": { path: 'get/worksheet/api/sheet/get/data', id: 13979, group: '默认分组' },
        "POST /worksheet/api/sheet/finish": { path: 'post/worksheet/api/sheet/finish/data', id: 14075, group: '默认分组' },
        "GET /worksheet/api/sheet/export": { path: 'get/worksheet/api/sheet/export/data', id: 17355, group: '默认分组' },
        "POST /worksheet/api/sheet/badge/reset": { path: 'post/worksheet/api/sheet/badge/reset/data', id: 13981, group: '默认分组' },
        "POST /worksheet/api/sheet/add": { path: 'post/worksheet/api/sheet/add/data', id: 13958, group: '默认分组' },
        "GET /worksheet/api/pool/list": { path: 'get/worksheet/api/pool/list/data', id: 13955, group: '默认分组' },
        "GET /worksheet/api/pending/list": { path: 'get/worksheet/api/pending/list/data', id: 13952, group: '默认分组' },
        "GET /worksheet/api/list/export": { path: 'get/worksheet/api/list/export/data', id: 27950, group: '默认分组' },
        "GET /worksheet/api/list": { path: 'get/worksheet/api/list/data', id: 27947, group: '默认分组' },
        "GET /worksheet/api/filter/list": { path: 'get/worksheet/api/filter/list/data', id: 27948, group: '默认分组' },
        "GET /worksheet/api/count": { path: 'get/worksheet/api/count/data', id: 27949, group: '默认分组' },
        "POST /worksheet/api/category/list/set": { path: 'post/worksheet/api/category/list/set/data', id: 25744, group: '默认分组' },
        "GET /worksheet/api/category/list/get": { path: 'get/worksheet/api/category/list/get/data', id: 25745, group: '默认分组' },
        "GET /worksheet/api/category/list": { path: 'get/worksheet/api/category/list/data', id: 13961, group: '默认分组' },
        "GET /worksheet/api/badge": { path: 'get/worksheet/api/badge/data', id: 14014, group: '默认分组' },
        "GET /wherever": { name: '官网-移动办公', index: 0, list: [{"id":12278,"path":"index\\whereever"}] },
        "GET /wechatService": { name: '接入微信客服', index: 0, list: [{"id":11231,"path":"index\\wechatService"}] },
        "GET /webda/da.gif": { path: 'get/webda/da.gif/data', id: 42390, group: '默认分组' },
        "POST /webapi/user/evaluate.action": { path: 'post/webapi/user/evaluate.action/data', id: 18111, group: '默认分组' },
        "GET /webapi/user/da/config": { path: 'get/webapi/user/da/config/data', id: 79828, group: '默认分组' },
        "GET /updateNotes": { name: '更新日志', index: 0, list: [{"id":10798,"path":"index\\updateNotes"}] },
        "GET /test/unit": { name: '官网-测试-样式预览-unit', index: 0, list: [{"id":14000,"path":"demos\\unit"}] },
        "GET /test": { name: '官网-测试-入口页面', index: 0, list: [{"id":14001,"path":"test\\index"}] },
        "GET /tempad/jobs": { name: '招贤纳士', index: 0, list: [{"id":14699,"path":"index\\jobs"}] },
        "GET /servicemarketing": { name: '官网-营销服务', index: 0, list: [{"id":14883,"path":"index\\servicemarketing"},{"id":14936,"path":"mobile\\servicemarketing"}] },
        "GET /service": { name: '官网-服务', index: 0, list: [{"id":12176,"path":"index\\service"}] },
        "GET /securitydetail": { name: '安全保障', index: 0, list: [{"id":14926,"path":"index\\securitydetail"}] },
        "GET /robot/api/questionCategory/list": { path: 'get/robot/api/questionCategory/list/data', id: 14300, group: '默认分组' },
        "POST /robot/api/questionCategory/edit": { path: 'post/robot/api/questionCategory/edit/data', id: 14302, group: '默认分组' },
        "POST /robot/api/questionCategory/del": { path: 'post/robot/api/questionCategory/del/data', id: 14303, group: '默认分组' },
        "POST /robot/api/questionCategory/add": { path: 'post/robot/api/questionCategory/add/data', id: 14301, group: '默认分组' },
        "GET /robot/api/question/list": { path: 'get/robot/api/question/list/data', id: 14299, group: '默认分组' },
        "GET /robot/api/question/get": { path: 'get/robot/api/question/get/data', id: 14343, group: '默认分组' },
        "POST /robot/api/question/edit": { path: 'post/robot/api/question/edit/data', id: 14305, group: '默认分组' },
        "POST /robot/api/question/del": { path: 'post/robot/api/question/del/data', id: 14372, group: '默认分组' },
        "POST /robot/api/question/check": { path: 'post/robot/api/question/check/data', id: 14344, group: '默认分组' },
        "POST /robot/api/question/add": { path: 'post/robot/api/question/add/data', id: 14304, group: '默认分组' },
        "GET /robot/api/optimize/word/list": { path: 'get/robot/api/optimize/word/list/data', id: 97064, group: '默认分组' },
        "POST /robot/api/optimize/word/import": { path: 'post/robot/api/optimize/word/import/data', id: 97735, group: '默认分组' },
        "POST /robot/api/optimize/word/edit": { path: 'post/robot/api/optimize/word/edit/data', id: 97084, group: '默认分组' },
        "POST /robot/api/optimize/word/deleteList": { path: 'post/robot/api/optimize/word/deleteList/data', id: 97715, group: '默认分组' },
        "POST /robot/api/optimize/word/delete": { path: 'post/robot/api/optimize/word/delete/data', id: 97079, group: '默认分组' },
        "POST /robot/api/optimize/word/add": { path: 'post/robot/api/optimize/word/add/data', id: 97103, group: '默认分组' },
        "POST /robot/api/issue/relative": { path: 'post/robot/api/issue/relative/data', id: 14307, group: '默认分组' },
        "GET /robot/api/issue/list": { path: 'get/robot/api/issue/list/data', id: 14330, group: '默认分组' },
        "POST /robot/api/issue/ignore": { path: 'post/robot/api/issue/ignore/data', id: 14308, group: '默认分组' },
        "GET /robot": { name: '官网-机器人', index: 0, list: [{"id":10999,"path":"index\\robot"},{"id":14016,"path":"mobile\\robot"}] },
        "GET /register/signup/mobile": { name: '官网注册-移动端适配入口 (测试用)', index: 0, list: [{"id":11162,"path":"register\\signupmobile"}] },
        "GET /register/signup": { name: '官网主页-注册登录', index: 0, list: [{"id":10851,"path":"register\\signup"},{"id":11162,"path":"register\\signupmobile"}] },
        "GET /register/service": { name: '官网-注册-用户协议', index: 0, list: [{"id":10753,"path":"register\\service"}] },
        "GET /register/registerResult": { name: '官网主页-注册-注册结果', index: 0, list: [{"id":10733,"path":"register\\registerResult"}] },
        "GET /register/refer": { name: '302跳转空页', index: 0, list: [{"id":10853,"path":"register\\refer"}] },
        "GET /register": { name: '官网主页-注册', index: 0, list: [{"id":10722,"path":"register\\index"}] },
        "GET /qa": { name: '常见问题', index: 0, list: [{"id":10799,"path":"index\\qa"}] },
        "GET /product/worksheet": { name: '产品-工单系统', index: 0, list: [{"id":11925,"path":"index\\worksheet"},{"id":14018,"path":"mobile\\worksheet"}] },
        "GET /product": { name: '官网系统- 产品页', index: 0, list: [{"id":10812,"path":"index\\product"}] },
        "GET /price/worksheet": { name: '工单价格页', index: 0, list: [{"id":13249,"path":"index\\priceWorksheet"}] },
        "GET /price/servicemarketing": { name: '营销服务价格页', index: 0, list: [{"id":15085,"path":"index\\priceServicemarketing"}] },
        "GET /price/robot": { name: '机器人价格页', index: 0, list: [{"id":13251,"path":"index\\priceRobot"}] },
        "GET /price/datamonitor": { name: '数据大屏价格页', index: 0, list: [{"id":15305,"path":"index\\priceDatamonitor"}] },
        "GET /price/callcenter": { name: '呼叫中心价格页', index: 0, list: [{"id":13250,"path":"index\\priceCallcenter"}] },
        "GET /price": { name: '官网系统-产品价格', index: 0, list: [{"id":10841,"path":"index\\price"},{"id":14020,"path":"mobile\\price"}] },
        "GET /online": { name: '在线客服', index: 0, list: [{"id":11723,"path":"index\\online"},{"id":14015,"path":"mobile\\online"}] },
        "GET /mobileda/da.gif": { path: 'get/mobileda/da.gif/data', id: 79050, group: '默认分组' },
        "GET /mobile": { name: '官网移动端适配', index: 0, list: [{"id":14014,"path":"mobile\\index"}] },
        "POST /mnst/college/videoForm": { path: 'post/mnst/college/videoForm/data', id: 22645, group: '轻学院' },
        "GET /mnst/api/wx/js/config": { path: 'get/mnst/api/wx/js/config/data', id: 44997, group: '专题页' },
        "POST /mnst/api/signup/submit": { path: 'post/mnst/api/signup/submit/data', id: 58286, group: '官网注册模块' },
        "POST /mnst/api/signup/sendCode": { path: 'post/mnst/api/signup/sendCode/data', id: 58145, group: '官网注册模块' },
        "POST /mnst/api/signup/next": { path: 'post/mnst/api/signup/next/data', id: 59501, group: '官网注册模块' },
        "GET /mnst/api/signup/checkPhone": { path: 'get/mnst/api/signup/checkPhone/data', id: 58972, group: '官网注册模块' },
        "GET /mnst/api/signup/checkEmail": { path: 'get/mnst/api/signup/checkEmail/data', id: 59507, group: '官网注册模块' },
        "GET /mnst/api/signup/checkDomain": { path: 'get/mnst/api/signup/checkDomain/data', id: 58281, group: '官网注册模块' },
        "POST /mnst/api/sendSmsCode": { path: 'post/mnst/api/sendSmsCode/data', id: 22344, group: '默认分组' },
        "POST /mnst/api/retry": { path: 'post/mnst/api/retry/data', id: 14323, group: '默认分组' },
        "POST /mnst/api/register": { path: 'post/mnst/api/register/data', id: 14280, group: '默认分组' },
        "POST /mnst/api/puzzle/validation": { path: 'post/mnst/api/puzzle/validation/data', id: 83488, group: '默认分组' },
        "GET /mnst/api/puzzle/picture": { path: 'get/mnst/api/puzzle/picture/data', id: 83487, group: '默认分组' },
        "GET /mnst/api/partner/trackedInviteeList": { path: 'get/mnst/api/partner/trackedInviteeList/data', id: 95682, group: '新合伙人' },
        "POST /mnst/api/partner/submitInvitee": { path: 'post/mnst/api/partner/submitInvitee/data', id: 95574, group: '新合伙人' },
        "GET /mnst/api/partner/signout": { path: 'get/mnst/api/partner/signout/data', id: 94765, group: '新合伙人' },
        "POST /mnst/api/partner/sign": { path: 'post/mnst/api/partner/sign/data', id: 94766, group: '新合伙人' },
        "GET /mnst/api/partner/sharedInviteeList": { path: 'get/mnst/api/partner/sharedInviteeList/data', id: 95583, group: '新合伙人' },
        "GET /mnst/api/partner/inviterInfo": { path: 'get/mnst/api/partner/inviterInfo/data', id: 96141, group: '新合伙人' },
        "POST /mnst/api/partner/editInviterInfo": { path: 'post/mnst/api/partner/editInviterInfo/data', id: 96730, group: '新合伙人' },
        "GET /mnst/api/merchants/getMap": { path: 'get/mnst/api/merchants/getMap/data', id: 20224, group: '默认分组' },
        "GET /mnst/api/merchants/getInfo": { path: 'get/mnst/api/merchants/getInfo/data', id: 20225, group: '默认分组' },
        "POST /mnst/api/market/presenter/add": { path: 'post/mnst/api/market/presenter/add/data', id: 42976, group: '工具集' },
        "POST /mnst/api/market/post/promoter/promotee": { path: 'post/mnst/api/market/post/promoter/promotee/data', id: 42628, group: '市场行为' },
        "POST /mnst/api/market/post/promoter": { path: 'post/mnst/api/market/post/promoter/data', id: 42624, group: '市场行为' },
        "POST /mnst/api/market/post/promotee": { path: 'post/mnst/api/market/post/promotee/data', id: 42629, group: '市场行为' },
        "GET /mnst/api/market/get/promoter": { path: 'get/mnst/api/market/get/promoter/data', id: 42631, group: '市场行为' },
        "POST /mnst/api/market/candidate/add": { path: 'post/mnst/api/market/candidate/add/data', id: 42984, group: '工具集' },
        "POST /mnst/api/logout": { path: 'post/mnst/api/logout/data', id: 14723, group: '默认分组' },
        "POST /mnst/api/login": { path: 'post/mnst/api/login/data', id: 14689, group: '默认分组' },
        "GET /mnst/api/live/uniqueness/get": { path: 'get/mnst/api/live/uniqueness/get/data', id: 22283, group: '专题页' },
        "POST /mnst/api/live/remind/post": { path: 'post/mnst/api/live/remind/post/data', id: 22282, group: '专题页' },
        "GET /mnst/api/live/polling": { path: 'get/mnst/api/live/polling/data', id: 22617, group: '默认分组' },
        "GET /mnst/api/live/outdate/get": { path: 'get/mnst/api/live/outdate/get/data', id: 27854, group: '专题页' },
        "POST /mnst/api/live/attend/post": { path: 'post/mnst/api/live/attend/post/data', id: 22280, group: '专题页' },
        "POST /mnst/api/live/attend/post": { path: 'post/mnst/api/live/attend/post/data', id: 42633, group: '市场行为' },
        "GET /mnst/api/kehu/case/getTitleList": { path: 'get/mnst/api/kehu/case/getTitleList/data', id: 25716, group: '默认分组' },
        "GET /mnst/api/getLoginStatus": { path: 'get/mnst/api/getLoginStatus/data', id: 14725, group: '默认分组' },
        "GET /mnst/api/getInviteCode": { path: 'get/mnst/api/getInviteCode/data', id: 18281, group: '默认分组' },
        "GET /mnst/api/getDomain": { path: 'get/mnst/api/getDomain/data', id: 15191, group: '默认分组' },
        "GET /mnst/api/getCaptchaStatus": { path: 'get/mnst/api/getCaptchaStatus/data', id: 15041, group: '默认分组' },
        "GET /mnst/api/form/get/validate/smsCode": { path: 'get/mnst/api/form/get/validate/smsCode/data', id: 42620, group: '工具集' },
        "GET /mnst/api/form/get/validate/mobile": { path: 'get/mnst/api/form/get/validate/mobile/data', id: 42617, group: '工具集' },
        "GET /mnst/api/form/get/smsCode": { path: 'get/mnst/api/form/get/smsCode/data', id: 42618, group: '工具集' },
        "GET /mnst/api/form/get/chinese2pinyin": { path: 'get/mnst/api/form/get/chinese2pinyin/data', id: 42599, group: '工具集' },
        "GET /mnst/api/form/captcha/get": { path: 'get/mnst/api/form/captcha/get/data', id: 42621, group: '工具集' },
        "GET /mnst/api/form/captcha/check": { path: 'get/mnst/api/form/captcha/check/data', id: 42622, group: '工具集' },
        "GET /mnst/api/demoCompany": { path: 'get/mnst/api/demoCompany/data', id: 21508, group: '默认分组' },
        "POST /mnst/api/completeInfo": { path: 'post/mnst/api/completeInfo/data', id: 14322, group: '默认分组' },
        "POST /mnst/api/college/userinfo": { path: 'post/mnst/api/college/userinfo/data', id: 22879, group: '默认分组' },
        "GET /mnst/api/captcha/new/check": { path: 'get/mnst/api/captcha/new/check/data', id: 22397, group: '专题页' },
        "GET /mnst/api/captcha/new": { path: 'get/mnst/api/captcha/new/data', id: 22379, group: '默认分组' },
        "GET /mnst/api/captcha": { path: 'get/mnst/api/captcha/data', id: 14281, group: '默认分组' },
        "POST /mnst/api/activity/qiLive1/save": { path: 'post/mnst/api/activity/qiLive1/save/data', id: 74395, group: '市场行为' },
        "GET /merchants": { name: '招商专题页', index: 0, list: [{"id":11924,"path":"index\\merchants"}] },
        "GET /market/promoter": { name: '推广人落地页', index: 0, list: [{"id":13838,"path":"market\\mobile\\promoter"},{"id":14003,"path":"activity\\invitation"}] },
        "GET /market/promotee": { name: '被推广人落地页', index: 0, list: [{"id":13837,"path":"market\\mobile\\promotee"},{"id":14004,"path":"activity\\partner"}] },
        "GET /kehu/yibangren": { name: '官网主页-客户-衣邦人', index: 0, list: [{"id":11459,"path":"index\\yibangren"}] },
        "GET /kehu/xiangchao": { name: '官网主页-客户-响巢看看', index: 0, list: [{"id":11458,"path":"index\\xiangchao"}] },
        "GET /kehu/linggou": { name: '官网主页-客户-零购', index: 0, list: [{"id":11456,"path":"index\\linggou"}] },
        "GET /kehu/fenlibao": { name: '官网主页-客户-分利宝', index: 0, list: [{"id":11455,"path":"index\\fenlibao"}] },
        "GET /kehu/fanhuan": { name: '官网主页-客户-返还网', index: 0, list: [{"id":11457,"path":"index\\fanhuan"}] },
        "GET /kehu/detail": { name: '案例详情页', index: 0, list: [{"id":12706,"path":"index\\kehuDetail"}] },
        "GET /kehu/davdian": { name: '官网-客户-大v店详情页', index: 0, list: [{"id":14467,"path":"index\\kehu_davdian"}] },
        "GET /kehu/17zuoye": { name: '官网-客户-一起作业 案例详情页', index: 0, list: [{"id":14468,"path":"index\\kehu_17zuoye"}] },
        "GET /kehu": { name: '官网主页-客户', index: 0, list: [{"id":11454,"path":"index\\kehu"}] },
        "GET /inviter/sign": { name: '新合伙人注册登录页', index: 0, list: [{"id":15111,"path":"partner\\inviter\\sign"},{"id":15112,"path":"partner\\inviter\\signMobile"}] },
        "GET /inviter/index": { name: '新合伙人详情首页', index: 0, list: [{"id":15113,"path":"partner\\inviter\\index"},{"id":15126,"path":"partner\\inviter\\indexMobile"}] },
        "GET /inviter/case": { name: '新合伙人落地页', index: 0, list: [{"id":15110,"path":"partner\\inviter\\case"},{"id":15118,"path":"partner\\inviter\\caseMobile"}] },
        "GET /guide": { name: '开发指南首页', index: 0, list: [{"id":11053,"path":"guide"}] },
        "GET /finance": { name: '互金解决方案', index: 0, list: [{"id":14963,"path":"index\\finance"}] },
        "GET /event/qi1": { name: '第一届qi大会', index: 0, list: [{"id":14783,"path":"activity\\qi1"},{"id":14784,"path":"activity\\qi1_mobile"}] },
        "GET /ehr": { name: 'ehr企业内部共享服务', index: 0, list: [{"id":14403,"path":"index\\ehr"}] },
        "GET /download": { name: '七鱼客服-下载页面', index: 0, list: [{"id":11036,"path":"download\\index"}] },
        "GET /doc": { name: '文档', index: 0, list: [{"id":11045,"path":"index\\doc"}] },
        "GET /copartner/invitation": { name: 'H5合伙人邀请页', index: 0, list: [{"id":13855,"path":"index\\copartner"}] },
        "GET /copartner/accepted": { name: 'H5合伙人接受邀请页', index: 0, list: [{"id":13865,"path":"index\\copartnerAccepted"}] },
        "GET /cooperation": { name: '合作伙伴页', index: 0, list: [{"id":12710,"path":"index\\partner"}] },
        "GET /conference": { name: '七鱼发布会', index: 0, list: [{"id":11046,"path":"conference\\index"}] },
        "GET /conduct/westkf": { name: '西游-宣传页', index: 0, list: [{"id":11534,"path":"conduct\\westkf"}] },
        "GET /college/detail": { name: '轻学院-详情页', index: 0, list: [{"id":12286,"path":"college\\detail"}] },
        "GET /college/": { name: '轻学院-首页', index: 0, list: [{"id":12284,"path":"college\\index"}] },
        "GET /callcenter": { name: '呼叫中心', index: 0, list: [{"id":11623,"path":"index\\prdCallcenter"},{"id":14019,"path":"mobile\\callcenter"}] },
        "GET /api/wx/token": { path: 'get/api/wx/token/data', id: 13624, group: '默认分组' },
        "POST /api/user/update": { path: 'post/api/user/update/data', id: 13159, group: '默认分组' },
        "GET /api/supervisor/sms/order/records": { path: 'get/api/supervisor/sms/order/records/data', id: 89325, group: '默认分组' },
        "GET /api/supervisor/sms/order/predefine": { path: 'get/api/supervisor/sms/order/predefine/data', id: 89195, group: '默认分组' },
        "GET /api/supervisor/sms/order/account": { path: 'get/api/supervisor/sms/order/account/data', id: 89315, group: '默认分组' },
        "GET /api/statistics/user/visitRecord/get": { path: 'get/api/statistics/user/visitRecord/get/data', id: 46766, group: '默认分组' },
        "GET /api/statistics/totalSessionsNums": { path: 'get/api/statistics/totalSessionsNums/data', id: 46624, group: '默认分组' },
        "GET /api/statistics/staffResolved": { path: 'get/api/statistics/staffResolved/data', id: 13646, group: '默认分组' },
        "GET /api/statistics/kefuGroup/report": { path: 'get/api/statistics/kefuGroup/report/data', id: 27960, group: '默认分组' },
        "GET /api/statistics/ipcc/report/seatWorkLoad": { path: 'get/api/statistics/ipcc/report/seatWorkLoad/data', id: 17688, group: '默认分组' },
        "GET /api/statistics/ipcc/report/seatStatus/summary": { path: 'get/api/statistics/ipcc/report/seatStatus/summary/data', id: 17690, group: '默认分组' },
        "GET /api/statistics/ipcc/report/seatStatus/list": { path: 'get/api/statistics/ipcc/report/seatStatus/list/data', id: 17691, group: '默认分组' },
        "GET /api/statistics/ipcc/report/seatStatus/history": { path: 'get/api/statistics/ipcc/report/seatStatus/history/data', id: 17689, group: '默认分组' },
        "GET /api/statistics/ipcc/report/seatEfficiency": { path: 'get/api/statistics/ipcc/report/seatEfficiency/data', id: 17680, group: '默认分组' },
        "GET /api/statistics/ipcc/report/responseMetrics": { path: 'get/api/statistics/ipcc/report/responseMetrics/data', id: 36326, group: '默认分组' },
        "GET /api/statistics/ipcc/report/ivrMonitor/list": { path: 'get/api/statistics/ipcc/report/ivrMonitor/list/data', id: 39472, group: '默认分组' },
        "GET /api/statistics/ipcc/report/ivrMonitor": { path: 'get/api/statistics/ipcc/report/ivrMonitor/data', id: 39222, group: '默认分组' },
        "GET /api/statistics/ipcc/report/callSummary": { path: 'get/api/statistics/ipcc/report/callSummary/data', id: 17679, group: '默认分组' },
        "GET /api/statistics/ipcc/report/callSessionNums": { path: 'get/api/statistics/ipcc/report/callSessionNums/data', id: 36276, group: '默认分组' },
        "GET /api/statistics/ipcc/report/callOutList": { path: 'get/api/statistics/ipcc/report/callOutList/data', id: 17686, group: '默认分组' },
        "GET /api/statistics/ipcc/report/callLossNums": { path: 'get/api/statistics/ipcc/report/callLossNums/data', id: 36316, group: '默认分组' },
        "GET /api/statistics/ipcc/report/callLossDetail": { path: 'get/api/statistics/ipcc/report/callLossDetail/data', id: 36317, group: '默认分组' },
        "GET /api/statistics/ipcc/report/callInList": { path: 'get/api/statistics/ipcc/report/callInList/data', id: 17684, group: '默认分组' },
        "GET /api/statistics/ipcc/report/callCategory": { path: 'get/api/statistics/ipcc/report/callCategory/data', id: 75453, group: '默认分组' },
        "GET /api/statistics/ipcc/ivrMonitor/selectList": { path: 'get/api/statistics/ipcc/ivrMonitor/selectList/data', id: 39236, group: '默认分组' },
        "GET /api/statistics/ipcc/ivrMonitor/queueList": { path: 'get/api/statistics/ipcc/ivrMonitor/queueList/data', id: 39234, group: '默认分组' },
        "GET /api/statistics/ipcc/export/seatWorkLoad": { path: 'get/api/statistics/ipcc/export/seatWorkLoad/data', id: 17710, group: '默认分组' },
        "GET /api/statistics/ipcc/export/seatEfficiency": { path: 'get/api/statistics/ipcc/export/seatEfficiency/data', id: 17708, group: '默认分组' },
        "GET /api/statistics/ipcc/export/callOutList": { path: 'get/api/statistics/ipcc/export/callOutList/data', id: 17693, group: '默认分组' },
        "GET /api/statistics/ipcc/export/callInList": { path: 'get/api/statistics/ipcc/export/callInList/data', id: 17692, group: '默认分组' },
        "POST /api/sms/sendMobileCode": { path: 'post/api/sms/sendMobileCode/data', id: 15654, group: '默认分组' },
        "POST /api/sms/sendImgCode": { path: 'post/api/sms/sendImgCode/data', id: 15673, group: '默认分组' },
        "POST /api/sms/registerMobile": { path: 'post/api/sms/registerMobile/data', id: 16518, group: '默认分组' },
        "POST /api/sms/register": { path: 'post/api/sms/register/data', id: 15633, group: '默认分组' },
        "POST /api/sms/code": { path: 'post/api/sms/code/data', id: 15624, group: '默认分组' },
        "POST /api/sms/checkMobile": { path: 'post/api/sms/checkMobile/data', id: 15643, group: '默认分组' },
        "POST /api/sms/checkEmail": { path: 'post/api/sms/checkEmail/data', id: 15641, group: '默认分组' },
        "POST /api/sms/checkDomain": { path: 'post/api/sms/checkDomain/data', id: 15642, group: '默认分组' },
        "GET /api/session/user": { path: 'get/api/session/user/data', id: 13235, group: '默认分组' },
        "POST /api/session/update": { path: 'post/api/session/update/data', id: 13160, group: '默认分组' },
        "GET /api/session/online": { path: 'get/api/session/online/data', id: 13132, group: '默认分组' },
        "POST /api/session/invite/save": { path: 'post/api/session/invite/save/data', id: 14084, group: '默认分组' },
        "GET /api/session/invite/get": { path: 'get/api/session/invite/get/data', id: 14083, group: '默认分组' },
        "GET /api/session/history": { path: 'get/api/session/history/data', id: 13136, group: '默认分组' },
        "POST /api/session/getMulti": { path: 'post/api/session/getMulti/data', id: 20719, group: '默认分组' },
        "GET /api/session/get": { path: 'get/api/session/get/data', id: 13175, group: '默认分组' },
        "POST /api/reply/update": { path: 'post/api/reply/update/data', id: 14897, group: '默认分组' },
        "GET /api/reply/list": { path: 'get/api/reply/list/data', id: 14894, group: '默认分组' },
        "POST /api/reply/import": { path: 'post/api/reply/import/data', id: 39930, group: '默认分组' },
        "GET /api/reply/export": { path: 'get/api/reply/export/data', id: 39931, group: '默认分组' },
        "POST /api/reply/del": { path: 'post/api/reply/del/data', id: 14895, group: '默认分组' },
        "GET /api/reply/checkExist": { path: 'get/api/reply/checkExist/data', id: 14898, group: '默认分组' },
        "POST /api/reply/category/update": { path: 'post/api/reply/category/update/data', id: 14891, group: '默认分组' },
        "GET /api/reply/category/list": { path: 'get/api/reply/category/list/data', id: 14892, group: '默认分组' },
        "POST /api/reply/category/del": { path: 'post/api/reply/category/del/data', id: 14889, group: '默认分组' },
        "POST /api/reply/category/add": { path: 'post/api/reply/category/add/data', id: 14890, group: '默认分组' },
        "POST /api/reply/add": { path: 'post/api/reply/add/data', id: 14896, group: '默认分组' },
        "POST /api/quality/update": { path: 'post/api/quality/update/data', id: 19321, group: '默认分组' },
        "POST /api/quality/setting/set": { path: 'post/api/quality/setting/set/data', id: 19320, group: '默认分组' },
        "GET /api/quality/setting/get": { path: 'get/api/quality/setting/get/data', id: 19318, group: '默认分组' },
        "POST /api/product/user": { path: 'post/api/product/user/data', id: 13306, group: '默认分组' },
        "GET /api/product/token": { path: 'get/api/product/token/data', id: 13316, group: '默认分组' },
        "POST /api/product/order": { path: 'post/api/product/order/data', id: 13142, group: '默认分组' },
        "GET /api/polling/task": { path: 'get/api/polling/task/data', id: 17277, group: '默认分组' },
        "GET /api/polling": { path: 'get/api/polling/data', id: 13161, group: '默认分组' },
        "GET /api/package/list": { path: 'get/api/package/list/data', id: 14663, group: '默认分组' },
        "POST /api/order/setting/setInfo": { path: 'post/api/order/setting/setInfo/data', id: 21402, group: '默认分组' },
        "GET /api/order/list": { path: 'get/api/order/list/data', id: 14642, group: '默认分组' },
        "POST /api/order/confirm": { path: 'post/api/order/confirm/data', id: 14643, group: '默认分组' },
        "POST /api/order/compose": { path: 'post/api/order/compose/data', id: 14656, group: '默认分组' },
        "GET /api/nos/media": { path: 'get/api/nos/media/data', id: 13654, group: '默认分组' },
        "GET /api/monitor/ignore": { path: 'get/api/monitor/ignore/data', id: 21758, group: '默认分组' },
        "POST /api/miniProgram/bind": { path: 'post/api/miniProgram/bind/data', id: 86326, group: '默认分组' },
        "GET /api/message/list": { path: 'get/api/message/list/data', id: 13138, group: '默认分组' },
        "GET /api/knowledge/search/count": { path: 'get/api/knowledge/search/count/data', id: 33440, group: '默认分组' },
        "GET /api/knowledge/question/search": { path: 'get/api/knowledge/question/search/data', id: 33189, group: '默认分组' },
        "POST /api/knowledge/question/import": { path: 'post/api/knowledge/question/import/data', id: 39299, group: '默认分组' },
        "GET /api/knowledge/question/get": { path: 'get/api/knowledge/question/get/data', id: 33277, group: '默认分组' },
        "GET /api/knowledge/question/export": { path: 'get/api/knowledge/question/export/data', id: 39302, group: '默认分组' },
        "POST /api/knowledge/point/import": { path: 'post/api/knowledge/point/import/data', id: 39301, group: '默认分组' },
        "GET /api/knowledge/point/get": { path: 'get/api/knowledge/point/get/data', id: 33275, group: '默认分组' },
        "GET /api/knowledge/point/export": { path: 'get/api/knowledge/point/export/data', id: 39304, group: '默认分组' },
        "POST /api/kefuGroup/updateKefus": { path: 'post/api/kefuGroup/updateKefus/data', id: 14044, group: '默认分组' },
        "POST /api/kefuGroup/update": { path: 'post/api/kefuGroup/update/data', id: 14043, group: '默认分组' },
        "GET /api/kefuGroup/list": { path: 'get/api/kefuGroup/list/data', id: 14046, group: '默认分组' },
        "GET /api/kefuGroup/kefuList": { path: 'get/api/kefuGroup/kefuList/data', id: 13960, group: '默认分组' },
        "POST /api/kefuGroup/deleteKefu": { path: 'post/api/kefuGroup/deleteKefu/data', id: 14052, group: '默认分组' },
        "POST /api/kefuGroup/delete": { path: 'post/api/kefuGroup/delete/data', id: 14041, group: '默认分组' },
        "POST /api/kefuGroup/add": { path: 'post/api/kefuGroup/add/data', id: 14039, group: '默认分组' },
        "POST /api/kefu/updateMobile": { path: 'post/api/kefu/updateMobile/data', id: 15651, group: '默认分组' },
        "POST /api/kefu/update": { path: 'post/api/kefu/update/data', id: 13157, group: '默认分组' },
        "POST /api/kefu/status": { path: 'post/api/kefu/status/data', id: 13167, group: '默认分组' },
        "POST /api/kefu/setting/callback/remind/time/set": { path: 'post/api/kefu/setting/callback/remind/time/set/data', id: 40113, group: '默认分组' },
        "GET /api/kefu/setting/callback/remind/time/get": { path: 'get/api/kefu/setting/callback/remind/time/get/data', id: 40109, group: '默认分组' },
        "POST /api/kefu/password": { path: 'post/api/kefu/password/data', id: 13166, group: '默认分组' },
        "GET /api/kefu/logout": { path: 'get/api/kefu/logout/data', id: 13165, group: '默认分组' },
        "POST /api/kefu/login": { path: 'post/api/kefu/login/data', id: 13164, group: '默认分组' },
        "GET /api/kefu/list": { path: 'get/api/kefu/list/data', id: 13158, group: '默认分组' },
        "POST /api/kefu/disable": { path: 'post/api/kefu/disable/data', id: 13417, group: '默认分组' },
        "POST /api/kefu/delete": { path: 'post/api/kefu/delete/data', id: 13156, group: '默认分组' },
        "POST /api/kefu/add": { path: 'post/api/kefu/add/data', id: 13155, group: '默认分组' },
        "GET /api/export/summaryReport": { path: 'get/api/export/summaryReport/data', id: 13151, group: '默认分组' },
        "GET /api/export/sessList": { path: 'get/api/export/sessList/data', id: 17314, group: '默认分组' },
        "GET /api/export/questionFeedback": { path: 'get/api/export/questionFeedback/data', id: 13152, group: '默认分组' },
        "GET /api/corporation/setting/robot/selectList": { path: 'get/api/corporation/setting/robot/selectList/data', id: 51418, group: '默认分组' },
        "POST /api/corporation/setting/leaveSetting": { path: 'post/api/corporation/setting/leaveSetting/data', id: 15114, group: '默认分组' },
        "GET /api/corporation/setting/getEvaluation": { path: 'get/api/corporation/setting/getEvaluation/data', id: 14402, group: '默认分组' },
        "POST /api/corporation/setting/evaluationmodel": { path: 'post/api/corporation/setting/evaluationmodel/data', id: 18108, group: '默认分组' },
        "POST /api/corporation/setting/evaluation": { path: 'post/api/corporation/setting/evaluation/data', id: 14400, group: '默认分组' },
        "POST /api/corporation/setting/evaInviteSwitch": { path: 'post/api/corporation/setting/evaInviteSwitch/data', id: 39292, group: '默认分组' },
        "POST /api/corporation/setting/crm/set": { path: 'post/api/corporation/setting/crm/set/data', id: 18526, group: '默认分组' },
        "GET /api/corporation/setting/crm/get": { path: 'get/api/corporation/setting/crm/get/data', id: 18523, group: '默认分组' },
        "POST /api/corpmsg/saveschedule": { path: 'post/api/corpmsg/saveschedule/data', id: 20101, group: '默认分组' },
        "POST /api/corpmsg/savemsg": { path: 'post/api/corpmsg/savemsg/data', id: 20106, group: '默认分组' },
        "GET /api/corpmsg/getschedulelist": { path: 'get/api/corpmsg/getschedulelist/data', id: 20099, group: '默认分组' },
        "GET /api/corpmsg/getmsglist": { path: 'get/api/corpmsg/getmsglist/data', id: 20105, group: '默认分组' },
        "POST /api/corpmsg/delschedule": { path: 'post/api/corpmsg/delschedule/data', id: 20104, group: '默认分组' },
        "POST /api/corpmsg/delmsg": { path: 'post/api/corpmsg/delmsg/data', id: 20108, group: '默认分组' },
        "POST /api/company/save": { path: 'post/api/company/save/data', id: 14641, group: '默认分组' },
        "POST /api/category/update": { path: 'post/api/category/update/data', id: 13183, group: '默认分组' },
        "POST /api/category/list/set": { path: 'post/api/category/list/set/data', id: 23634, group: '默认分组' },
        "GET /api/category/list/get": { path: 'get/api/category/list/get/data', id: 23632, group: '默认分组' },
        "GET /api/category/list": { path: 'get/api/category/list/data', id: 13181, group: '默认分组' },
        "POST /api/category/delete": { path: 'post/api/category/delete/data', id: 13182, group: '默认分组' },
        "POST /api/category/add": { path: 'post/api/category/add/data', id: 13173, group: '默认分组' },
        "POST /api/callcenter/unmonitor": { path: 'post/api/callcenter/unmonitor/data', id: 28119, group: '默认分组' },
        "POST /api/callcenter/tts/save": { path: 'post/api/callcenter/tts/save/data', id: 30166, group: '默认分组' },
        "GET /api/callcenter/tts/list": { path: 'get/api/callcenter/tts/list/data', id: 30163, group: '默认分组' },
        "POST /api/callcenter/tts/delete": { path: 'post/api/callcenter/tts/delete/data', id: 30167, group: '默认分组' },
        "GET /api/callcenter/transfer": { path: 'get/api/callcenter/transfer/data', id: 20714, group: '默认分组' },
        "POST /api/callcenter/sip/set": { path: 'post/api/callcenter/sip/set/data', id: 28408, group: '默认分组' },
        "GET /api/callcenter/sip/list": { path: 'get/api/callcenter/sip/list/data', id: 28455, group: '默认分组' },
        "GET /api/callcenter/sip/get": { path: 'get/api/callcenter/sip/get/data', id: 28409, group: '默认分组' },
        "POST /api/callcenter/settingvoice/set": { path: 'post/api/callcenter/settingvoice/set/data', id: 17659, group: '默认分组' },
        "GET /api/callcenter/settingvoice/get": { path: 'get/api/callcenter/settingvoice/get/data', id: 17658, group: '默认分组' },
        "POST /api/callcenter/setting/set": { path: 'post/api/callcenter/setting/set/data', id: 17068, group: '默认分组' },
        "GET /api/callcenter/setting/get": { path: 'get/api/callcenter/setting/get/data', id: 17067, group: '默认分组' },
        "GET /api/callcenter/session/user": { path: 'get/api/callcenter/session/user/data', id: 17668, group: '默认分组' },
        "POST /api/callcenter/session/unmute": { path: 'post/api/callcenter/session/unmute/data', id: 18561, group: '默认分组' },
        "POST /api/callcenter/session/transfer": { path: 'post/api/callcenter/session/transfer/data', id: 20893, group: '默认分组' },
        "POST /api/callcenter/session/mute": { path: 'post/api/callcenter/session/mute/data', id: 18560, group: '默认分组' },
        "GET /api/callcenter/session/detail": { path: 'get/api/callcenter/session/detail/data', id: 17275, group: '默认分组' },
        "POST /api/callcenter/session/check": { path: 'post/api/callcenter/session/check/data', id: 20905, group: '默认分组' },
        "POST /api/callcenter/outcall": { path: 'post/api/callcenter/outcall/data', id: 17341, group: '默认分组' },
        "POST /api/callcenter/monitor": { path: 'post/api/callcenter/monitor/data', id: 28117, group: '默认分组' },
        "POST /api/callcenter/ivrsetting/set": { path: 'post/api/callcenter/ivrsetting/set/data', id: 17072, group: '默认分组' },
        "GET /api/callcenter/ivrsetting/list": { path: 'get/api/callcenter/ivrsetting/list/data', id: 30393, group: '默认分组' },
        "GET /api/callcenter/ivrsetting/get": { path: 'get/api/callcenter/ivrsetting/get/data', id: 17070, group: '默认分组' },
        "POST /api/callcenter/ivrsetting/del": { path: 'post/api/callcenter/ivrsetting/del/data', id: 30395, group: '默认分组' },
        "POST /api/callcenter/ivrMonitor/queue/set": { path: 'post/api/callcenter/ivrMonitor/queue/set/data', id: 39237, group: '默认分组' },
        "GET /api/callcenter/history": { path: 'get/api/callcenter/history/data', id: 17079, group: '默认分组' },
        "GET /api/callcenter/failedCallList": { path: 'get/api/callcenter/failedCallList/data', id: 30157, group: '默认分组' },
        "GET /api/callcenter/distribution/get": { path: 'get/api/callcenter/distribution/get/data', id: 21358, group: '默认分组' },
        "GET /api/callcenter/costmode": { path: 'get/api/callcenter/costmode/data', id: 17676, group: '默认分组' },
        "POST /api/callcenter/conference/unmute": { path: 'post/api/callcenter/conference/unmute/data', id: 112444, group: '默认分组' },
        "POST /api/callcenter/conference/mute": { path: 'post/api/callcenter/conference/mute/data', id: 112440, group: '默认分组' },
        "POST /api/callcenter/conference/delmember": { path: 'post/api/callcenter/conference/delmember/data', id: 112457, group: '默认分组' },
        "POST /api/callcenter/conference/create": { path: 'post/api/callcenter/conference/create/data', id: 112458, group: '默认分组' },
        "POST /api/callcenter/conference/addmember": { path: 'post/api/callcenter/conference/addmember/data', id: 112454, group: '默认分组' },
        "GET /api/callcenter/callseat": { path: 'get/api/callcenter/callseat/data', id: 17677, group: '默认分组' },
        "GET /api/callcenter/callcost": { path: 'get/api/callcenter/callcost/data', id: 17666, group: '默认分组' },
        "GET /api/callcenter/callback/task/todaycount": { path: 'get/api/callcenter/callback/task/todaycount/data', id: 40115, group: '默认分组' },
        "POST /api/callcenter/callback/task/edit": { path: 'post/api/callcenter/callback/task/edit/data', id: 40122, group: '默认分组' },
        "POST /api/callcenter/callback/task/delay": { path: 'post/api/callcenter/callback/task/delay/data', id: 40130, group: '默认分组' },
        "POST /api/callcenter/callback/task/create": { path: 'post/api/callcenter/callback/task/create/data', id: 40120, group: '默认分组' },
        "POST /api/callcenter/callback/task/cancel": { path: 'post/api/callcenter/callback/task/cancel/data', id: 40123, group: '默认分组' },
        "GET /api/callcenter/callback/list": { path: 'get/api/callcenter/callback/list/data', id: 40116, group: '默认分组' },
        "POST /api/callcenter/callModeSetting/set": { path: 'post/api/callcenter/callModeSetting/set/data', id: 21329, group: '默认分组' },
        "GET /api/callcenter/callModeSetting/get": { path: 'get/api/callcenter/callModeSetting/get/data', id: 21325, group: '默认分组' },
        "GET /api/announce/list": { path: 'get/api/announce/list/data', id: 18449, group: '默认分组' },
        "GET /activity/speakOut": { name: '活动页-吐槽大赛', index: 0, list: [{"id":12239,"path":"activity\\speakOut"}] },
        "GET /activity/partner": { name: '合伙人首页', index: 0, list: [{"id":13901,"path":"activity\\partner"}] },
        "GET /activity/oneKeyReach": { name: '专题页 - 一键直达', index: 0, list: [{"id":13319,"path":"activity\\oneKeyReach"}] },
        "GET /activity/live": { name: '活动页-直播', index: 0, list: [{"id":12231,"path":"activity\\live"},{"id":12236,"path":"activity\\liveMobile"}] },
        "GET /activity/invitation": { name: '合伙人接收邀请页面', index: 0, list: [{"id":13902,"path":"activity\\invitation"}] },
        "GET /activity/awards": { name: '专题-客户颁奖盛典2017-01', index: 0, list: [{"id":12529,"path":"activity\\awards"}] },
        "GET /activity/anniversary": { name: '活动页-周年庆', index: 0, list: [{"id":12985,"path":"activity\\anniversary"}] },
        "GET /activity": { name: '官网活动页面', index: 0, list: [{"id":11560,"path":"index\\activity"}] },
        "GET /": { name: '官网主页', index: 0, list: [{"id":10606,"path":"index\\index"},{"id":14014,"path":"mobile\\index"}] },
        "GET ": { path: 'get/data', id: 14082, group: '默认分组' },
    },
    /* 注入给页面的模型数据的服务器配置 */
    // modelServer: {
    //     // 完整的主机地址，包括协议、主机名、端口
    //     host: '',
    //     // 查询参数，键值对
    //     queries: {},
    //     // 自定义请求头，键值对
    //     headers: {},
    //     // path 可以是字符串，也可以是函数；默认不用传，即使用 host + 页面path + queries 的值
    //     // 如果是函数，则使用函数的返回值，传给函数的参数 options 是一个对象，它包含 host、path（页面path）、queries、headers 等参数
    //     // 如果 path 的值为假值，则使用 host + 页面path + queries 的值；
    //     // 如果 path 的值是相对地址，则会在前面加上 host
    //     // path: '',
    // },
    /* api 响应头 */
    apiResHeaders: {
        // 设置可跨域访问时，取消注释以下内容, 并按需要配置
        // 'Access-Control-Allow-Origin': 'http://localhost:8080',
        // 'Access-Control-Allow-Credentials': 'true',
        // 'Access-Control-Allow-Headers': 'Content-Type',
        // 'Access-Control-Allow-Methods': 'GET, POST, HEAD, OPTIONS, PUT, DELETE, PATCH'
    },
    /* 是否自动打开浏览器 */
    launch: false,
    /* 自动打开的页面地址 */
    openUrl: '',
    /* 端口 */
    port: 8002,
    /* 是否使用 https 协议，设为true的时候表示启用 */
    https: false,
    /* 是否使用 nei 提供的在线 mock 数据 */
    online: false,
    /* 是否监听静态文件和模板文件的变化并自动刷新浏览器 */
    reload: false,
    /* 文件监听的选项 */
    watchingFiles: {
        /* 需要即时编译的文件, 前提是 reload 为 true */
        compilers: {
            /* 值为 mcss 的配置选项, 默认为 false，即不编译 mcss 文件 */
            mcss: false
        },
        /* 不用监听的文件，支持通配符 */
        //ignored: '**/*.css'
    },
    /* 项目的 key */
    projectKey: '73eeeb4a6af8870d920acf3fb2f1de98',
    /* 同步模块mock数据路径 */
    mockTpl: '/Users/guoquankai/webProject/mainsite-test4/source/mock/mockTpl/',
    /* 异步接口mock数据路径 */
    mockApi: '/Users/guoquankai/mainsite-test4/source/mock/mockApi/',
    /* 模板后缀 */
    viewExt: '.ftl',
    /* 模板引擎 */
    engine: 'freemarker',
    /* 打开下面的 fmpp 配置，可以在模板中调用自定义 jar 包中的类 */
    //fmpp: {
    //    /* 存放自定义 jar 的目录, 绝对路径 */
    //    jarDir: '',
    //    /* 暴露给模板的类实例名称和 jar 中的类名(带包名)的对应关系 */
    //    jarConfig: {
    //        [暴露给模板的类实例名称]: [类名] // 比如: HighlightUtil: 'yueduutil.HighlightUtil'
    //    }
    //}
};